"""
Closed-vocab bridge: FOLIO clause types + ODRL rights/duties + PROV-O provenance.

Key entities:
- Clause (root): One operative contract clause.
- Jurisdiction: The governing-law jurisdiction(s): the name plus whether one or multiple laws govern.

Key relationships:
- Clause --BOUNDED_BY--> TemporalConstraint
- Clause --HAS_CAPS--> CapConstraint
- Clause --GOVERNED_BY--> Jurisdiction

Generated by docling-graph template generation from src/rag_wright/ontology/contract_bridge.ttl.
"""

import logging
import re
from enum import Enum
from typing import Any, List, Optional, Type

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing_extensions import Self

logger = logging.getLogger(__name__)


# -----------------------------------------------------------------------------
# Docling Graph edge helper
# -----------------------------------------------------------------------------
def edge(
    label: str,
    default: Any = None,
    *,
    reference: bool = False,
    closed_catalog: bool = False,
    **kwargs: Any,
) -> Any:
    """
    Declare a field as a graph edge for Docling-Graph via json_schema_extra.

    ``reference=True`` marks an identity-ONLY link (graph_reference): the field
    carries id-only references to entities described in full elsewhere in the
    schema. In dense extraction these references are filled by the PARENT's own
    fill call (never discovered separately), which preserves per-parent
    membership lists and avoids phantom parents.

    ``closed_catalog=True`` (reference_closed_catalog) declares that the targets
    form a CLOSED catalog defined elsewhere in the document: a target that only
    exists through this field (never instantiated or referenced otherwise) is a
    hallucinated member — the converter then drops the edge (and the orphaned
    target), unless that would wipe more than half of the target class.
    """
    json_schema_extra = dict(kwargs.pop("json_schema_extra", {}) or {})
    json_schema_extra["edge_label"] = label
    if reference:
        json_schema_extra["graph_reference"] = True
    if closed_catalog:
        json_schema_extra["reference_closed_catalog"] = True

    if "default_factory" in kwargs:
        default_factory = kwargs.pop("default_factory")
        return Field(default_factory=default_factory, json_schema_extra=json_schema_extra, **kwargs)

    return Field(default, json_schema_extra=json_schema_extra, **kwargs)


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
def _normalize_enum(enum_cls: Type[Enum], v: Any) -> Any:
    """
    Accept enum instances, value strings, or member names.
    Handles various formats: 'VALUE', 'value', 'Value', 'VALUE_NAME'.
    Falls back to the OTHER member instead of rejecting (never raises).
    """
    if isinstance(v, enum_cls):
        return v
    if isinstance(v, str):
        key = re.sub(r"[^A-Za-z0-9]+", "", v).lower()
        mapping: dict[str, Any] = {}
        for member in enum_cls:
            mapping[re.sub(r"[^A-Za-z0-9]+", "", member.name).lower()] = member
            mapping[re.sub(r"[^A-Za-z0-9]+", "", str(member.value)).lower()] = member
        if key in mapping:
            return mapping[key]
    if "OTHER" in enum_cls.__members__:
        logger.warning("Unmapped enum value %r for %s; falling back to OTHER", v, enum_cls.__name__)
        return enum_cls.OTHER
    return v


# -----------------------------------------------------------------------------
# Enums
# -----------------------------------------------------------------------------
class Subject(str, Enum):
    """Controlled vocabulary for subject values. Unmapped values normalize to OTHER."""

    IP_INFRINGEMENT = "ip_infringement"
    TRADEMARK = "trademark"
    COPYRIGHT = "copyright"
    VIOLATION_OF_LAW = "violation_of_law"
    FRAUD = "fraud"
    GROSS_NEGLIGENCE = "gross_negligence"
    OTHER = "Other"


class PartyScope(str, Enum):
    """Controlled vocabulary for party_scope values. Unmapped values normalize to OTHER."""

    AFFILIATES = "affiliates"
    LICENSOR_AFFILIATES = "licensor_affiliates"
    LICENSEE_AFFILIATES = "licensee_affiliates"
    OTHER = "Other"


class ExceptionModel(str, Enum):
    """Controlled vocabulary for exception_model values. Unmapped values normalize to OTHER."""

    INDEMNIFICATION = "indemnification"
    CONFIDENTIALITY = "confidentiality"
    THIRD_PARTY_IP_INFRINGEMENT = "third_party_ip_infringement"
    FRAUD = "fraud"
    GROSS_NEGLIGENCE = "gross_negligence"
    WILLFUL_MISCONDUCT = "willful_misconduct"
    BODILY_INJURY = "bodily_injury"
    APPLICABLE_LAW = "applicable_law"
    OTHER = "Other"


class AssignmentConsent(str, Enum):
    """Controlled vocabulary for assignment_consent values. Unmapped values normalize to OTHER."""

    CONSENT_REQUIRED = "consent_required"
    NOTICE_ONLY = "notice_only"
    FREE = "free"
    OTHER = "Other"


class Asymmetry(str, Enum):
    """Controlled vocabulary for asymmetry values. Unmapped values normalize to OTHER."""

    SYMMETRIC = "symmetric"
    DIFFERENT_PER_PARTY = "different_per_party"
    OTHER = "Other"


class ClaimScope(str, Enum):
    """Controlled vocabulary for claim_scope values. Unmapped values normalize to OTHER."""

    FIRST_PARTY = "first_party"
    THIRD_PARTY = "third_party"
    BROAD_BASED = "broad_based"
    OTHER = "Other"


class CocConsent(str, Enum):
    """Controlled vocabulary for coc_consent values. Unmapped values normalize to OTHER."""

    CONSENT_REQUIRED = "consent_required"
    NOTICE_ONLY = "notice_only"
    UNRESTRICTED = "unrestricted"
    OTHER = "Other"


class EscrowReleaseTrigger(str, Enum):
    """Controlled vocabulary for escrow_release_trigger values. Unmapped values normalize to OTHER."""

    BANKRUPTCY = "bankruptcy"
    BREACH = "breach"
    DISCONTINUANCE = "discontinuance"
    OTHER = "Other"


class ExclusivityType(str, Enum):
    """Controlled vocabulary for exclusivity_type values. Unmapped values normalize to OTHER."""

    EXCLUSIVE = "exclusive"
    SOLE = "sole"
    NON_EXCLUSIVE = "non_exclusive"
    OTHER = "Other"


class Favorability(str, Enum):
    """Controlled vocabulary for favorability values. Unmapped values normalize to OTHER."""

    BUYER_FAVORABLE = "buyer_favorable"
    SELLER_FAVORABLE = "seller_favorable"
    OTHER = "Other"


class IpOwnership(str, Enum):
    """Controlled vocabulary for ip_ownership values. Unmapped values normalize to OTHER."""

    ASSIGNED = "assigned"
    JOINT = "joint"
    RETAINED = "retained"
    OTHER = "Other"


class MfnScope(str, Enum):
    """Controlled vocabulary for mfn_scope values. Unmapped values normalize to OTHER."""

    PRICE = "price"
    TERMS = "terms"
    PRICE_AND_TERMS = "price_and_terms"
    OTHER = "Other"


class Mutuality(str, Enum):
    """Controlled vocabulary for mutuality values. Unmapped values normalize to OTHER."""

    MUTUAL = "mutual"
    UNILATERAL = "unilateral"
    OTHER = "Other"


class RenewalMechanism(str, Enum):
    """Controlled vocabulary for renewal_mechanism values. Unmapped values normalize to OTHER."""

    AUTO = "auto"
    REQUIRES_NOTICE = "requires_notice"
    OTHER = "Other"


class RestrictionScope(str, Enum):
    """Controlled vocabulary for restriction_scope values. Unmapped values normalize to OTHER."""

    GEOGRAPHIC = "geographic"
    ACTIVITY = "activity"
    GEOGRAPHIC_AND_ACTIVITY = "geographic_and_activity"
    OTHER = "Other"


class RightOfFirstType(str, Enum):
    """Controlled vocabulary for right_of_first_type values. Unmapped values normalize to OTHER."""

    ROFR = "rofr"
    ROFO = "rofo"
    ROFN = "rofn"
    OTHER = "Other"


class TerminationRight(str, Enum):
    """Controlled vocabulary for termination_right values. Unmapped values normalize to OTHER."""

    EITHER_PARTY = "either_party"
    ONE_PARTY = "one_party"
    OTHER = "Other"


class WarrantyScope(str, Enum):
    """Controlled vocabulary for warranty_scope values. Unmapped values normalize to OTHER."""

    IMPLIED = "implied"
    EXPRESS = "express"
    AS_IS = "as_is"
    NON_RELIANCE = "non_reliance"
    OTHER = "Other"


class DamageType(str, Enum):
    """Controlled vocabulary for damage_type values. Unmapped values normalize to OTHER."""

    INDIRECT = "indirect"
    CONSEQUENTIAL = "consequential"
    INCIDENTAL = "incidental"
    PUNITIVE = "punitive"
    SPECIAL = "special"
    OTHER = "Other"


class NonsolicitTarget(str, Enum):
    """Controlled vocabulary for nonsolicit_target values. Unmapped values normalize to OTHER."""

    EMPLOYEES = "employees"
    CUSTOMERS = "customers"
    OTHER = "Other"


class ProceduralDuty(str, Enum):
    """Controlled vocabulary for procedural_duty values. Unmapped values normalize to OTHER."""

    DUTY_TO_DEFEND = "duty_to_defend"
    CONTROL_OF_DEFENSE = "control_of_defense"
    OTHER = "Other"


class CapBasis(str, Enum):
    """Controlled vocabulary for cap_basis values. Unmapped values normalize to OTHER."""

    FIXED_FEE = "fixed_fee"
    MULTIPLE_OF_FEES = "multiple_of_fees"
    CAP_OTHER = "cap_other"
    OTHER = "Other"


class LawMultiplicity(str, Enum):
    """Controlled vocabulary for law_multiplicity values. Unmapped values normalize to OTHER."""

    SINGLE = "single"
    MULTIPLE = "multiple"
    OTHER = "Other"


# -----------------------------------------------------------------------------
# Components
# -----------------------------------------------------------------------------
class CapConstraint(BaseModel):
    """
    The liability cap: its basis plus the open quantum (e.g. '12 months of fees', '$1,000,000').
    """

    model_config = ConfigDict(is_entity=False)

    cap_basis: CapBasis = Field(
        CapBasis.OTHER,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    cap_operator: Optional[str] = Field(
        None,
        max_length=40,
        description="The comparison operator ONLY (a few words), e.g. 'lteq' (at most), 'eq' (fixed).",
    )

    cap_quantum: Optional[str] = Field(
        None,
        max_length=80,
        description="The cap amount ONLY (a short value, not a sentence), e.g. '12_months', '1x_fees', "
        "'$1,000,000'.",
    )

    @field_validator("cap_basis", mode="before")
    @classmethod
    def _normalize_cap_basis(cls, v: Any) -> Any:
        """Map free-text values onto CapBasis members (falls back to OTHER)."""
        return _normalize_enum(CapBasis, v)

    def __str__(self) -> str:
        parts = [self.cap_operator, self.cap_quantum]
        return " ".join(str(p) for p in parts if p) or "Unknown"


class TemporalConstraint(BaseModel):
    """A time bound on the clause: a term/duration or a notice period."""

    model_config = ConfigDict(is_entity=False)

    temporal_duration: Optional[str] = Field(
        None,
        max_length=60,
        description="The duration ONLY (a short value), e.g. '12_months', '30_days', 'unbounded'.",
    )

    temporal_kind: Optional[str] = Field(
        None,
        max_length=40,
        description="What is bounded: 'term' (temporal_bound) or 'notice_period'.",
    )

    temporal_operator: Optional[str] = Field(
        None,
        max_length=40,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    def __str__(self) -> str:
        parts = [self.temporal_duration, self.temporal_kind]
        return " ".join(str(p) for p in parts if p) or "Unknown"


# -----------------------------------------------------------------------------
# Entities
# -----------------------------------------------------------------------------
class Jurisdiction(BaseModel):
    """The governing-law jurisdiction(s): the name plus whether one or multiple laws govern."""

    model_config = ConfigDict(graph_id_fields=["jurisdiction_name"])

    jurisdiction_name: str = Field(
        ...,
        max_length=100,
        description="The jurisdiction NAME ONLY (a few words, not a sentence), e.g. 'New York', "
        "'England and Wales', 'Delaware'.",
        examples=["New York", "England and Wales", "Delaware"],
    )

    law_multiplicity: LawMultiplicity = Field(
        LawMultiplicity.OTHER,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    @field_validator("law_multiplicity", mode="before")
    @classmethod
    def _normalize_law_multiplicity(cls, v: Any) -> Any:
        """Map free-text values onto LawMultiplicity members (falls back to OTHER)."""
        return _normalize_enum(LawMultiplicity, v)

    def __str__(self) -> str:
        parts = [self.jurisdiction_name]
        return " ".join(str(p) for p in parts if p) or "Unknown"


# -----------------------------------------------------------------------------
# Root document
# -----------------------------------------------------------------------------
class Clause(BaseModel):
    """
    One operative contract clause. Its function/type is known from the classifier; this template
    extracts the clause's typed properties, each read verbatim from the clause text.
    """

    model_config = ConfigDict(graph_id_fields=["document_reference"])

    document_reference: Optional[str] = Field(
        None,
        max_length=80,
        description=(
            "OPTIONAL. ONLY the clause's own section number or short heading if one is written in the "
            "text (e.g. 'Section 8', '8.1 Limitation of Liability'). If there is NO explicit section "
            "number or heading, leave this null/empty -- do NOT invent one and NEVER quote the clause "
            "body or any sentence of it here."
        ),
        examples=[
            "Section 8",
            "8.1 Limitation of Liability",
            "Governing Law",
        ],
    )

    audit_frequency: Optional[str] = Field(
        None,
        max_length=60,
        description=(
            "How often an audit-rights clause permits audits, a short value ONLY, e.g. 'annual', "
            "'quarterly', 'once per year'."
        ),
    )

    clause_type: Optional[str] = Field(
        None,
        max_length=80,
        description=(
            "The clause function/type LABEL ONLY (a few words), e.g. 'Cap on Liability', "
            "'Governing Law', 'Non-Solicit of Employees'."
        ),
    )

    commitment_quantum: Optional[str] = Field(
        None,
        max_length=80,
        description=(
            "The minimum-commitment / volume amount ONLY (a short value), e.g. '$1,000,000', "
            "'100 units/year'."
        ),
    )

    covers: List[Subject] = Field(
        default_factory=list,
        description="Subjects the clause covers (ODRL target; may be several).",
    )

    covers_party_scope: PartyScope = Field(
        PartyScope.OTHER,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    excepts: List[ExceptionModel] = Field(
        default_factory=list,
        description="Carve-outs / exceptions the clause lists (may be several).",
    )

    has_assignment_consent: AssignmentConsent = Field(
        AssignmentConsent.OTHER,
        description="How an anti-assignment clause treats consent (required / notice-only / free).",
    )

    has_asymmetry: Asymmetry = Field(
        Asymmetry.OTHER,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    has_claim_scope: ClaimScope = Field(
        ClaimScope.OTHER,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    has_coc_consent: CocConsent = Field(
        CocConsent.OTHER,
        description=(
            "How a change-of-control clause treats consent (required / notice-only / unrestricted)."
        ),
    )

    has_escrow_release_trigger: EscrowReleaseTrigger = Field(
        EscrowReleaseTrigger.OTHER,
        description=(
            "What triggers a source-code escrow release (bankruptcy / breach / discontinuance)."
        ),
    )

    has_exclusivity_type: ExclusivityType = Field(
        ExclusivityType.OTHER,
        description=(
            "The exclusivity a licensing/distribution clause grants (exclusive / sole / "
            "non-exclusive)."
        ),
    )

    has_favorability: Favorability = Field(
        Favorability.OTHER,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    has_ip_ownership: IpOwnership = Field(
        IpOwnership.OTHER,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    has_mfn_scope: MfnScope = Field(
        MfnScope.OTHER,
        description="What a most-favored-nation clause covers (price / terms / both).",
    )

    has_mutuality: Mutuality = Field(
        Mutuality.OTHER,
        description=(
            "Whether the clause's obligation runs both ways (mutual) or one way (unilateral)."
        ),
    )

    has_renewal: RenewalMechanism = Field(
        RenewalMechanism.OTHER,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    has_restriction_scope: RestrictionScope = Field(
        RestrictionScope.OTHER,
        description="What a non-compete restricts: geographic area, activity, or both.",
    )

    has_right_of_first_type: RightOfFirstType = Field(
        RightOfFirstType.OTHER,
        description=(
            "The first-refusal/offer/negotiation right the clause grants (ROFR / ROFO / ROFN)."
        ),
    )

    has_termination_right: TerminationRight = Field(
        TerminationRight.OTHER,
        description="Who may terminate for convenience (either party / one party).",
    )

    has_warranty_scope: WarrantyScope = Field(
        WarrantyScope.OTHER,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    ld_trigger: Optional[str] = Field(
        None,
        description="What triggers liquidated damages, e.g. 'late delivery', 'early termination'.",
    )

    prohibits_damage: List[DamageType] = Field(
        default_factory=list,
        description="Damage types the clause waives/excludes (may be several).",
    )

    prohibits_solicit: NonsolicitTarget = Field(
        NonsolicitTarget.OTHER,
        description="Whom the clause forbids soliciting (employees / customers).",
    )

    requires_duty: ProceduralDuty = Field(
        ProceduralDuty.OTHER,
        description="A procedural duty the clause imposes (duty to defend / control of defense).",
    )

    bounded_by: Optional[TemporalConstraint] = edge(
        label="BOUNDED_BY",
        description="A temporal bound (term or notice period), if any.",
    )

    caps: Optional[CapConstraint] = edge(
        label="HAS_CAPS",
        description="The liability cap, if any.",
    )

    governed_by: Optional[Jurisdiction] = edge(
        label="GOVERNED_BY",
        description="The governing-law jurisdiction, if the clause states one.",
    )

    @field_validator("covers", mode="before")
    @classmethod
    def _normalize_covers(cls, v: Any) -> Any:
        """Map free-text list items onto Subject members (falls back to OTHER)."""
        if isinstance(v, list):
            return [_normalize_enum(Subject, item) for item in v]
        return _normalize_enum(Subject, v)

    @field_validator("covers_party_scope", mode="before")
    @classmethod
    def _normalize_covers_party_scope(cls, v: Any) -> Any:
        """Map free-text values onto PartyScope members (falls back to OTHER)."""
        return _normalize_enum(PartyScope, v)

    @field_validator("excepts", mode="before")
    @classmethod
    def _normalize_excepts(cls, v: Any) -> Any:
        """Map free-text list items onto ExceptionModel members (falls back to OTHER)."""
        if isinstance(v, list):
            return [_normalize_enum(ExceptionModel, item) for item in v]
        return _normalize_enum(ExceptionModel, v)

    @field_validator("has_assignment_consent", mode="before")
    @classmethod
    def _normalize_has_assignment_consent(cls, v: Any) -> Any:
        """Map free-text values onto AssignmentConsent members (falls back to OTHER)."""
        return _normalize_enum(AssignmentConsent, v)

    @field_validator("has_asymmetry", mode="before")
    @classmethod
    def _normalize_has_asymmetry(cls, v: Any) -> Any:
        """Map free-text values onto Asymmetry members (falls back to OTHER)."""
        return _normalize_enum(Asymmetry, v)

    @field_validator("has_claim_scope", mode="before")
    @classmethod
    def _normalize_has_claim_scope(cls, v: Any) -> Any:
        """Map free-text values onto ClaimScope members (falls back to OTHER)."""
        return _normalize_enum(ClaimScope, v)

    @field_validator("has_coc_consent", mode="before")
    @classmethod
    def _normalize_has_coc_consent(cls, v: Any) -> Any:
        """Map free-text values onto CocConsent members (falls back to OTHER)."""
        return _normalize_enum(CocConsent, v)

    @field_validator("has_escrow_release_trigger", mode="before")
    @classmethod
    def _normalize_has_escrow_release_trigger(cls, v: Any) -> Any:
        """Map free-text values onto EscrowReleaseTrigger members (falls back to OTHER)."""
        return _normalize_enum(EscrowReleaseTrigger, v)

    @field_validator("has_exclusivity_type", mode="before")
    @classmethod
    def _normalize_has_exclusivity_type(cls, v: Any) -> Any:
        """Map free-text values onto ExclusivityType members (falls back to OTHER)."""
        return _normalize_enum(ExclusivityType, v)

    @field_validator("has_favorability", mode="before")
    @classmethod
    def _normalize_has_favorability(cls, v: Any) -> Any:
        """Map free-text values onto Favorability members (falls back to OTHER)."""
        return _normalize_enum(Favorability, v)

    @field_validator("has_ip_ownership", mode="before")
    @classmethod
    def _normalize_has_ip_ownership(cls, v: Any) -> Any:
        """Map free-text values onto IpOwnership members (falls back to OTHER)."""
        return _normalize_enum(IpOwnership, v)

    @field_validator("has_mfn_scope", mode="before")
    @classmethod
    def _normalize_has_mfn_scope(cls, v: Any) -> Any:
        """Map free-text values onto MfnScope members (falls back to OTHER)."""
        return _normalize_enum(MfnScope, v)

    @field_validator("has_mutuality", mode="before")
    @classmethod
    def _normalize_has_mutuality(cls, v: Any) -> Any:
        """Map free-text values onto Mutuality members (falls back to OTHER)."""
        return _normalize_enum(Mutuality, v)

    @field_validator("has_renewal", mode="before")
    @classmethod
    def _normalize_has_renewal(cls, v: Any) -> Any:
        """Map free-text values onto RenewalMechanism members (falls back to OTHER)."""
        return _normalize_enum(RenewalMechanism, v)

    @field_validator("has_restriction_scope", mode="before")
    @classmethod
    def _normalize_has_restriction_scope(cls, v: Any) -> Any:
        """Map free-text values onto RestrictionScope members (falls back to OTHER)."""
        return _normalize_enum(RestrictionScope, v)

    @field_validator("has_right_of_first_type", mode="before")
    @classmethod
    def _normalize_has_right_of_first_type(cls, v: Any) -> Any:
        """Map free-text values onto RightOfFirstType members (falls back to OTHER)."""
        return _normalize_enum(RightOfFirstType, v)

    @field_validator("has_termination_right", mode="before")
    @classmethod
    def _normalize_has_termination_right(cls, v: Any) -> Any:
        """Map free-text values onto TerminationRight members (falls back to OTHER)."""
        return _normalize_enum(TerminationRight, v)

    @field_validator("has_warranty_scope", mode="before")
    @classmethod
    def _normalize_has_warranty_scope(cls, v: Any) -> Any:
        """Map free-text values onto WarrantyScope members (falls back to OTHER)."""
        return _normalize_enum(WarrantyScope, v)

    @field_validator("prohibits_damage", mode="before")
    @classmethod
    def _normalize_prohibits_damage(cls, v: Any) -> Any:
        """Map free-text list items onto DamageType members (falls back to OTHER)."""
        if isinstance(v, list):
            return [_normalize_enum(DamageType, item) for item in v]
        return _normalize_enum(DamageType, v)

    @field_validator("prohibits_solicit", mode="before")
    @classmethod
    def _normalize_prohibits_solicit(cls, v: Any) -> Any:
        """Map free-text values onto NonsolicitTarget members (falls back to OTHER)."""
        return _normalize_enum(NonsolicitTarget, v)

    @field_validator("requires_duty", mode="before")
    @classmethod
    def _normalize_requires_duty(cls, v: Any) -> Any:
        """Map free-text values onto ProceduralDuty members (falls back to OTHER)."""
        return _normalize_enum(ProceduralDuty, v)

    @model_validator(mode="after")
    def _deduplicate_covers(self) -> Self:
        """Keep first occurrence per key (removes duplicates from chunked extraction)."""
        if not self.covers:
            return self
        seen: set[str] = set()
        unique: list[Any] = []
        for item in self.covers:
            key = str(item).strip().lower()
            if key not in seen:
                seen.add(key)
                unique.append(item)
        object.__setattr__(self, "covers", unique)
        return self

    @model_validator(mode="after")
    def _deduplicate_excepts(self) -> Self:
        """Keep first occurrence per key (removes duplicates from chunked extraction)."""
        if not self.excepts:
            return self
        seen: set[str] = set()
        unique: list[Any] = []
        for item in self.excepts:
            key = str(item).strip().lower()
            if key not in seen:
                seen.add(key)
                unique.append(item)
        object.__setattr__(self, "excepts", unique)
        return self

    @model_validator(mode="after")
    def _deduplicate_prohibits_damage(self) -> Self:
        """Keep first occurrence per key (removes duplicates from chunked extraction)."""
        if not self.prohibits_damage:
            return self
        seen: set[str] = set()
        unique: list[Any] = []
        for item in self.prohibits_damage:
            key = str(item).strip().lower()
            if key not in seen:
                seen.add(key)
                unique.append(item)
        object.__setattr__(self, "prohibits_damage", unique)
        return self

    def __str__(self) -> str:
        parts = [self.document_reference, self.audit_frequency]
        return " ".join(str(p) for p in parts if p) or "Unknown"


# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------
# This template passed generation gates V1-V6 (parse, import allowlist,
# load, structured-output schema, dense catalog walk, graph-shape smoke
# test). Comments never reach extraction prompts — only class docstrings
# and field descriptions do. After hand edits, re-verify with:
#
#     docling-graph template lint <module.path.Clause>
